main_project/main_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from reddit_clone import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.post_list, name="post_list"),
    path('reddit_clone/',include('reddit_clone.urls',namespace="reddit_clone")),
    path('login/',views.user_login,name="user_login"),
    path('logout/',views.user_logout,name="user_logout"),
    path('register/',views.register,name="register"),


    #password reset hehe xd
    # path('password_reset/',auth_views.PasswordResetView.as_view(template_name='registration/PasswordResetView.html') ,name='password_reset'),
    # path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='registration/PasswordResetDoneView.html'),name='password_reset_done'),
    # path('password_reset/confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='registration/PasswordResetConfirmView.html'),name='PasswordResetConfirmView'),
    # path('password_reset/complete/',auth_views.PasswordResetCompleteView.as_view(template_name='registration/PasswordResetCompleteView.html'),name='password_reset_complete'),

    path('',include('django.contrib.auth.urls')),
    path('upvote/<int:id>/',views.upvote,name="upvote"),
    path('downvote/<int:id>/',views.downvote,name="downvote"),

]

main_project/reddit_clone/urls.py
from django.urls import path
from reddit_clone import views

app_name='reddit_clone'

urlpatterns = [
    path('<id>/post_edit/',views.post_edit,name="post_edit"),
    path('<int:id>/post_delete/',views.post_delete,name="post_delete"),
    path('<id>/comment_edit/',views.comment_edit,name="comment_edit"),
    path('<int:id>/comment_delete/',views.comment_delete,name="comment_delete"),
    path('<int:id>/<slug:slug>/',views.post_detail, name="post_detail"),
    path('post_create/',views.post_create,name="post_create"),
]

main_project/reddit_clone/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status="published")


class Post(models.Model):
    objects = models.Manager()
    published = PublishedManager()


    STATUS_CHOICES = (
        ('draft','Draft'),
        ('published','Published'),
    )

    title   =   models.CharField(max_length=100)
    slug    =   models.SlugField(max_length=120)
    author  =   models.ForeignKey(User,on_delete=models.CASCADE,related_name='reddit_posts')
    body    =   models.TextField()
    votes   =   models.IntegerField(default=0)
    created =   models.DateTimeField(auto_now_add=True)
    updated =   models.DateTimeField(auto_now=True)
    status  =   models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("reddit_clone:post_detail", args=[self.id,self.slug])



@receiver(pre_save,sender=Post)
def pre_save_slug(sender, **kwargs):
    slug=slugify(kwargs['instance'].title)
    kwargs['instance'].slug=slug

class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    reply = models.ForeignKey('self',on_delete=models.CASCADE ,null=True,related_name="replies")
    content = models.TextField(max_length=160)
    timestamp=models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return '{}-{}'.format(self.post.title,str(self.user.username))

main_project/reddit_clone/forms.py
from django import forms
from .models import Post, Comment
from django.contrib.auth.models import User

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'title',
            'body',
            'status',
        )

class PostEditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'title',
            'body',
            'status',
        )

class UserLoginForm(forms.Form):
    username = forms.CharField(label="Username:")
    password = forms.CharField(label="Password:", widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Enter password'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Confirm password'}))
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
        )
    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match!")
        return confirm_password

class CommentForm(forms.ModelForm):
    content = forms.CharField(label="",widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Write a comment','rows':'4','cols':'50'}))
    class Meta:
        model = Comment
        fields = ('content',)

class CommentEditForm(forms.ModelForm):
    content = forms.CharField(label="",widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Write a comment','rows':'4','cols':'50'}))
    class Meta:
        model = Comment
        fields = ('content',)

main_project/reddit_clone/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from datetime import datetime
from .models import Post, Comment
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

def post_list(request):
    post_list = Post.published.all()
    query = request.GET.get('q')
    if query:
        post_list = Post.published.filter(title__icontains=query)

    paginator = Paginator(post_list, 10)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)


    if page is None:
        start_index=0
        end_index =5
    else:
        (start_index,end_index) = proper_pagination(posts,index=3)
    
    page_range = list(paginator.page_range)[start_index:end_index]

    context = {
        'posts':posts,
        'page_range':page_range,
    }
    return render(request,'reddit_clone/post_list.html',context)


def proper_pagination(posts,index):
    start_index=0
    end_index=5
    if posts.number >index:
        start_index = posts.number - index
        end_index = start_index + end_index
    return(start_index, end_index)



def post_detail(request,id,slug):
    post = get_object_or_404(Post,id=id,slug=slug)
    comments = Comment.objects.filter(post=post,reply=None).order_by('-id')

    # if post.votes.filter(id=request.user.id).exists():
    #     is_voted = True
    if request.method == 'POST':
        comment_form=CommentForm(request.POST or None)
        if comment_form.is_valid():
            content = request.POST.get('content')
            reply_id = request.POST.get('comment_id')
            comment_qs = None
            if reply_id:
                comment_qs=Comment.objects.get(id=reply_id)
            comment=Comment.objects.create(post=post,user=request.user,content=content,reply=comment_qs)
            comment.save()
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        comment_form=CommentForm()

    context = {
        'post':post,
        'comments':comments,
        'comment_form':comment_form,
    }
    return render(request,'reddit_clone/post_detail.html',context)

def comment_edit(request,id):
    post = get_object_or_404(Post,id=id)
    comment=get_object_or_404(Comment,id=id)
    if request.user.id != comment.user_id:
        raise Http404()
    if request.method == "POST":
        comment_form = CommentEditForm(request.POST or None, instance=comment)
        if comment_form.is_valid():
            comment.save()
            return HttpResponseRedirect(reverse('post_list'))
    else:
        comment_form = CommentEditForm(instance=comment)
    context = {
        'post':post,
        'comment':comment,
        'comment_form':comment_form,
    }
    return render(request,'reddit_clone/comment_edit.html',context)

def comment_delete(request, id):
    post = get_object_or_404(Post,id=id)
    comment=get_object_or_404(Comment,id=id)
    if request.user.id != comment.user_id:
        raise Http404()
    comment.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))



# def vote_post(request):
#     post = get_object_or_404(Post,id=request.POST.get('post_id'))
#     is_voted=False
#     if post.votes.filter(id=request.user.id).exists():
#         post.votes.remove(request.user)
#         is_voted=False
#     else:
#         post.votes.add(request.user)
#         is_voted=True
#    return HttpResponseRedirect(post.get_absolute_url())

def upvote(request,id):
    return cast_vote(request,id,+1)

def downvote(request,id):
    return cast_vote(request,id,-1)

def cast_vote(request,id,score):
    post = get_object_or_404(Post,id=id)
    post.votes+=score
    post.save()
    return HttpResponseRedirect(post.get_absolute_url())


def post_create(request):
    if request.method == 'POST':
        form = PostCreateForm(request.POST)
        if form.is_valid():
            post=form.save(commit=False)
            post.author = request.user
            post.save()
    else:
        form = PostCreateForm()
    context = {
        'form':form,
    }
    return render(request,'reddit_clone/post_create.html',context)

def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username,password=password)
            if user:
                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect(reverse('post_list'))
                else:
                    return HttpResponse("User is not active")
            else:
                return HttpResponse("User with that name/password doesn't exist!")
    else:
        form =UserLoginForm()
    
    context = {
        'form':form,
    }
    return render(request, 'reddit_clone/login.html',context)


def user_logout(request):
    logout(request)
    return redirect('post_list')

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            return redirect('post_list')
    else:
        form = UserRegistrationForm()
    context = {
        'form': form,
    }
    return render(request,'registration/register.html',context)



def post_edit(request,id):
    post = get_object_or_404(Post,id=id)
    if post.author != request.user:
        raise Http404()
    if request.method == "POST":
        form = PostEditForm(request.POST or None, instance=post)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        form = PostEditForm(instance=post)
    context = {
        'form':form,
        'post':post,
    }
    return render(request,'reddit_clone/post_edit.html',context)

def post_delete(request, id):
    post=get_object_or_404(Post,id=id)
    if request.user != post.author:
        raise Http404()
    post.delete()
    return redirect('post_list')

main_project/templates/reddit_clone/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>  
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Reddit Clone{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'reddit_clone/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>

{% include 'reddit_clone/navbar.html' %}

    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script type="text/javascript">
            $('#delete').click(function(){
                return confirm("Are you sure you want to delete this post?");
            });

            $('#delete1').click(function(){
                return confirm("Are you sure you want to delete this comment?");
            });

            $('.reply-btn').click(function(){
                $(this).parent().parent().next('.replied-comments').fadeToggle()
            });

    </script>

</body>
</html>

main_project/templates/reddit_clone/comment_edit.html
{% extends 'reddit_clone/base.html' %}

{% block title  %} Edit Comment {% endblock %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <input type="submit" value="Update" class="btn btn-success">

</form>


{% endblock %}

main_project/templates/reddit_clone/login.html
{% extends 'reddit_clone/base.html' %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <small>
        <a href="{% url 'register' %}">Register</a> | 
        <a href="{% url 'password_reset' %}">Forgotten Your Password?</a>
    </small>
    <br>
    <input type="submit" value="Login" class="btn btn-outline-success">

</form>


{% endblock %}

main_project/templates/reddit_clone/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'post_list' %}">Reddit Clone</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <form class="form-inline my-2 my-lg-0" action='{% url "post_list" %}'>
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
      </ul>
      <ul class="navbar-nav">
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span>Hello {{ request.user|capfirst }}</span>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'reddit_clone:post_create' %}">Create Post</a>
            <a class="dropdown-item" href="{% url 'user_logout' %}">Logout</a>
          </div>
        </li>
        {% else %}
          <li class="nav-item">
              <a href="{% url 'user_login' %}" class="nav-link"> Login</a>

          </li>
        {% endif %}
      </ul>
    </div>
  </nav>

main_project/templates/reddit_clone/post_create.html
{% extends 'reddit_clone/base.html' %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" class="btn btn-outline-success">

</form>




{% endblock %}

main_project/templates/reddit_clone/post_detail.html
{% extends 'reddit_clone/base.html' %}


{% block title  %} {{ post.title }} | {{ block.super }} {% endblock %}

{% block content %}

<h3>{{ post.title }}</h3>
<small>Created by: {{ post.author }}</small>
<hr>
<p>{{ post.body }}</p>

{{ total_votes }}

{% if request.user.is_authenticated %}
    <form action="{% url 'upvote' post.id%}" method="post">
      {% csrf_token %}
      <input type="submit" value="Vote up">
    </form>

    <hr>
      <h4>This post has score of {{ post.votes }} votes!</h4>
    <hr>

    <form action="{% url 'downvote' post.id%}" method="post">
      {% csrf_token %}
      <input type="submit" value="Vote down">
    </form>
{% endif %}

{% if post.author == request.user%}

<div class="section-1" style="float: right;">
    <a href="{% url 'reddit_clone:post_edit' id=post.id %}">
      <button type="button" class="btn btn-outline-success">Edit</button>
    </a>
    <a href="{% url 'reddit_clone:post_delete' id=post.id%}" id="delete">
      <button type="button" class="btn btn-danger">Delete</button>
    </a>
</div>
{% endif %}



<br><br>
<hr>


<!--here goes commenting on a post-->
<div class="main-comment-section">
  <div class="container-fluid mt-2">
    <div class="form-group row">
      <form method="post">
        {% csrf_token %}
        {{ comment_form.as_p }}
        {% if request.user.is_authenticated  %}
          <input type="submit" value="Submit" class="btn btn-outline-success">
        {% else %}
          <input type="submit" value="Submit" class="btn btn-outline-success" disabled>
        {% endif %}
      
      </form>
    </div>
  </div>
  <!--here counts comments on post-->
  {{ comments.count }} Comment {{ comments|pluralize }}
  <!--here loops through comments on post-->
  {% for comment in comments %}
    <blockquote class="blockquote">
      <p class="mb-0"> <small>{{ comment.content }}</small></p>
      <footer class="blockquote-footer"><small>By <cite title="Source Title">{{ comment.user|capfirst }}</cite></small>
        <button type="button" name="button" class="reply-btn btn btn-outline-dark btn-sm ml-2">Reply</button>
        {% if comment.user_id == request.user.id %}
        <a href="{% url 'reddit_clone:comment_edit' id=comment.id %}">
          <button type="button" class="btn btn-outline-success btn-sm ml-2">Edit</button>
        </a>
        <a href="{% url 'reddit_clone:comment_delete' id=comment.id%}" id="delete1">
            <button type="button" class="btn btn-danger btn-sm ml-2">Delete</button>
        </a>
        {% endif %}

      </footer>
    </blockquote>

    <div class="replied-comments container mt-2" style="display: none;">
      <!--here loops through replys on post-->
      {% for reply in comment.replies.all %}
      <blockquote class="blockquote">
        <p class="mb-0"> <small>{{ reply.content }}</small></p>
        <footer class="blockquote-footer"><small>By <cite title="Source Title">{{ reply.user|capfirst }}</cite></small>
          <button type="button" name="button" class="reply-btn2 btn btn-outline-dark btn-sm ml-2">Reply</button>
          {% if comment.user_id == request.user.id %}
            {% if comment.reply_id != NULL %}
            <a href="{% url 'reddit_clone:comment_edit' id=comment.reply_id %}">
              <button type="button" class="btn btn-outline-success btn-sm ml-2">Edit</button>
            </a>
            <a href="{% url 'reddit_clone:comment_delete' id=comment.reply_id%}" id="delete1">
              <button type="button" class="btn btn-danger btn-sm ml-2">Delete</button>
            </a>
            {% endif %}
          {% endif %}
        </footer>
      </blockquote>

      {% endfor %}
      <!-- commenting form || also used for replying-->
      <div class="form-group row">
        <form method="post">
          {% csrf_token %}
          <input type="hidden" name="comment_id" value="{{ comment.id }}">
          {{ comment_form.as_p }}
          {% if request.user.is_authenticated  %}
            <input type="submit" value="Submit" class="btn btn-outline-success">
          {% else %}
            <input type="submit" value="Submit" class="btn btn-outline-success" disabled>
          {% endif %}
        </form>
      </div>

    </div>
  {% endfor %}

</div>




{% endblock %}

main_project/templates/reddit_clone/post_edit.html
{% extends 'reddit_clone/base.html' %}

{% block title  %} {{ post.title }} | Edit {% endblock %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" class="btn btn-success">

</form>


{% endblock %}

main_project/templates/reddit_clone/post_list.html
{% extends 'reddit_clone/base.html' %}

{% block title  %} Welcome to {{ block.super }} {% endblock %}

{% block content %}

<div class="row">
    {% for p in posts%}
    <div class="col-md-6">
        <div class="img-thumbnail">
            <a href="{{ p.get_absolute_url }}">{{ p.title }}</a><small style="float:right">{{ p.created }}</small><br>
            Author: {{ p.author }}
            <br>
            {{ p.body }}
        </div>
        <br>
    </div>
    {% endfor %}
<ul class="pagination">
    {% if posts.has_previous %}
        <li class="page-item ">
            <a href="?page={{ posts.previous_page_number }}" class="page-link">&laquo;</a>
        </li>
    {% endif %}


    {% for p in posts.paginator.page_range %}
        {% if posts.number == p %}
            <li class="page-item active">
                <a href="?page={{ p }}" class="page-link">{{ p }}</a>
            </li>
        {% else %}
            <li class="page-item">
                <a href="?page={{ p }}" class="page-link">{{ p }}</a>
            </li>
        {% endif %}

    {% endfor %}
    {% if posts.has_next %}
    <li class="page-item ">
        <a href="?page={{ posts.next_page_number }}" class="page-link">&raquo;</a>
    </li>
    {% endif %}


</ul>

</div>

{% endblock %}